[package]
name = "pyrite"
version = "0.1.0"
authors = ["block <block@tortoise-games.com>"]
edition = "2018"

[dependencies]
num = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true}

[dev-dependencies]
proptest = "0.8.7"
serde_json = "1.0"
