[package]
name = "pyr-math-derive"
version = "0.1.0"
authors = ["block <block.cube.lib@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["full", "extra-traits", "visit-mut", "visit"] }
